import type { Metadata, Viewport } from "next";
import { Gabarito, Hubot_Sans } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const gabarito = Gabarito({
	variable: "--font-gabarito",
	subsets: ["latin"],
	weight: "variable",
});

const hubot = Hubot_Sans({
	variable: "--font-hubot",
	subsets: ["latin"],
	weight: "variable",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	maximumScale: 1,
	initialScale: 1,
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${gabarito.variable} ${hubot.variable} font-hubot antialiased`}>
				<NextTopLoader
					color="#73eaff"
					shadow="0 0 10px #73eaff,0 0 5px #73eaff"
				/>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
